#schema des Factures
Facture:
  definition:
    fields:
      _id: {}
      _rev: {}
      type: {}
      identifiant: {}
      date_emission: {}
      date_facturation: {}
      campagne: {}
      nb_page: {type: integer}
      statut: {}
      emetteur:
        type: collection
        definition:
          fields:
            adresse: {}
            code_postal: {}
            ville: {}
            service_facturation: {}
            telephone: {}
      client_identifiant: {}
      client_reference: {}
      client:
        type: collection
        definition:
          fields:
            raison_sociale: {}
            adresse: {}
            code_postal: {}
            ville: {}
      total_ht: {type: float}
      total_ttc: {type: float}
      lignes:
        type: collection
        definition:
          fields:
            '*':
              class: FactureLignes
              type: array_collection
              definition:
                fields:
                  '*':
                    class: FactureLigne
                    type: collection
                    definition:
                      fields:
                        origine_type: {}
                        origine_identifiant: {}
                        origine_libelle: {}
                        origine_date: {}
                        produit_type: {}
                        produit_libelle: {}
                        produit_hash: {}
                        contrat_identifiant: {}
                        contrat_libelle: {}
                        echeance_code: {}
                        volume: {type: float}
                        cotisation_taux: {type: float}
                        montant_ht: {type: float}
                        origine_mouvements:
                          type: array_collection
                          definition:
                            fields:
                              '*':  { }
      echeances:
        type: array_collection
        definition:
          fields:
            '*':
              type: collection
              definition:
                fields:
                  echeance_code: {}
                  echeance_date: {}
                  montant_ttc: {type: float}
      origines:
        type: collection
        definition:
          fields:
            #DRM ou SRV ID => "libelle"
            '*': {}
