#schema des Factures
Facture:
  definition:
    fields:
      _id: {}
      _rev: {}
      type: {}
      identifiant: {}
      date_emission: {}
      date_facturation: {}
      campagne: {}
      emetteur:
        type: collection
        definition:
          fields:
            adresse: {}
            code_postal: {}
            ville: {}
            service_facturation: {}
            telephone: {}
      client_identifiant: {}
      client_reference: {}
      client:
        type: collection
        definition:
          fields:
            raison_sociale: {}
            adresse: {}
            code_postal: {}
            ville: {}
      total_ht: {type: float}
      total_ttc: {type: float}
      lignes:
        type: array_collection
        definition:
          fields:
            '*':
              type: collection
              class: FactureLigne
              definition:
                fields:
                  origine_type: {}
                  origine_identifiant: {}
                  origine_date: {}
                  produit_type: {}
                  produit_libelle: {}
                  produit_hash: {}
                  mouvement_type: {}
                  contrat_identifiant: {}
                  contrat_libelle: {}
                  echeance_code: {}
                  volume: {type: float}
                  cotisation_taux: {type: float}
                  montant_ht: {type: float}
                  cle_mouvement: {}
      echeances:
        type: array_collection
        definition:
          fields:
            '*':
              type: collection
              definition:
                fields:
                  echeance_code: {}
                  echeance_date: {}
                  montant_ttc: {type: float}
      origines:
        type: collection
        definition:
          fields:
            #DRM ou SRV ID => "libelle"
            '*': {}
